/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.heuboe.vinfo.viewer;

import de.heuboe.vinfo.viewer.logic.CellRenderer;
import de.heuboe.vinfo.viewer.logic.Controller;
import de.heuboe.vinfo.viewer.logic.System;
import de.heuboe.vinfo.viewer.logic.Util;
import de.heuboe.vinfo.viewer.logic.ViewerException;
import de.heuboe.vinfo.viewer.logic.ViewerTableModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author peter_2
 */
public class VInfoViewer extends javax.swing.JDialog 
{
    private System system = System.instance();
    
    /**
     * Creates new form NewJDialog
     */
    public VInfoViewer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelMainG = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jTabbedPaneViews = new javax.swing.JTabbedPane();
        jPanelTabT = new javax.swing.JPanel();
        jPanelTabTopT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanelTabBottomT = new javax.swing.JPanel();
        jButtonCloseTabT = new javax.swing.JButton();
        jButtonDeleteAllT = new javax.swing.JButton();
        jButtonColumnChoiceT = new javax.swing.JButton();
        jPanelTabTableT = new javax.swing.JPanel();
        jScrollPaneT = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelBottomG = new javax.swing.JPanel();
        jButtonConfig = new javax.swing.JButton();
        jButtonNewView = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemNewView = new javax.swing.JMenuItem();
        jMenuItemConfig = new javax.swing.JMenuItem();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelMainG.setLayout(new java.awt.BorderLayout());

        jTabbedPaneViews.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 1, 1));

        jPanelTabT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanelTabT.setLayout(new java.awt.BorderLayout());

        jPanelTabTopT.setPreferredSize(new java.awt.Dimension(429, 50));

        jLabel1.setText("Filter");
        jLabel1.setAlignmentX(0.5F);

        jTextField2.setText("jTextField2");

        jButton4.setText("Aktualisieren");
        jButton4.setMaximumSize(new java.awt.Dimension(93, 20));
        jButton4.setMinimumSize(new java.awt.Dimension(93, 20));
        jButton4.setPreferredSize(new java.awt.Dimension(93, 20));

        javax.swing.GroupLayout jPanelTabTopTLayout = new javax.swing.GroupLayout(jPanelTabTopT);
        jPanelTabTopT.setLayout(jPanelTabTopTLayout);
        jPanelTabTopTLayout.setHorizontalGroup(
            jPanelTabTopTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabTopTLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTabTopTLayout.setVerticalGroup(
            jPanelTabTopTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabTopTLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanelTabTopTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jTextField2.getAccessibleContext().setAccessibleName("");

        jPanelTabT.add(jPanelTabTopT, java.awt.BorderLayout.NORTH);

        jPanelTabBottomT.setPreferredSize(new java.awt.Dimension(533, 40));

        jButtonCloseTabT.setText("Schließen");
        jButtonCloseTabT.setToolTipText("");
        jButtonCloseTabT.setMaximumSize(new java.awt.Dimension(87, 23));
        jButtonCloseTabT.setMinimumSize(new java.awt.Dimension(87, 23));
        jButtonCloseTabT.setPreferredSize(new java.awt.Dimension(87, 23));

        jButtonDeleteAllT.setText("Alle löschen");
        jButtonDeleteAllT.setToolTipText("");
        jButtonDeleteAllT.setMaximumSize(new java.awt.Dimension(87, 23));
        jButtonDeleteAllT.setMinimumSize(new java.awt.Dimension(87, 23));
        jButtonDeleteAllT.setPreferredSize(new java.awt.Dimension(87, 23));

        jButtonColumnChoiceT.setText("Spaltenauswahl");
        jButtonColumnChoiceT.setToolTipText("");
        jButtonColumnChoiceT.setActionCommand("");
        jButtonColumnChoiceT.setMaximumSize(new java.awt.Dimension(87, 23));
        jButtonColumnChoiceT.setMinimumSize(new java.awt.Dimension(87, 23));
        jButtonColumnChoiceT.setPreferredSize(new java.awt.Dimension(87, 23));
        jButtonColumnChoiceT.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openColumnChoiceConfig(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabBottomTLayout = new javax.swing.GroupLayout(jPanelTabBottomT);
        jPanelTabBottomT.setLayout(jPanelTabBottomTLayout);
        jPanelTabBottomTLayout.setHorizontalGroup(
            jPanelTabBottomTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabBottomTLayout.createSequentialGroup()
                .addGap(0, 233, Short.MAX_VALUE)
                .addComponent(jButtonColumnChoiceT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteAllT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCloseTabT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelTabBottomTLayout.setVerticalGroup(
            jPanelTabBottomTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabBottomTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTabBottomTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCloseTabT, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteAllT, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonColumnChoiceT, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTabT.add(jPanelTabBottomT, java.awt.BorderLayout.SOUTH);

        jPanelTabTableT.setPreferredSize(new java.awt.Dimension(533, 250));
        jPanelTabTableT.setLayout(new java.awt.BorderLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneT.setViewportView(jTable1);

        jPanelTabTableT.add(jScrollPaneT, java.awt.BorderLayout.CENTER);

        jPanelTabT.add(jPanelTabTableT, java.awt.BorderLayout.CENTER);

        jTabbedPaneViews.addTab("tab1", jPanelTabT);

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneViews)
                .addContainerGap())
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneViews, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        jPanelMainG.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jButtonConfig.setText("Konfiguration");
        jButtonConfig.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openConfigDlg(evt);
            }
        });

        jButtonNewView.setText("Neuer View");
        jButtonNewView.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newTab(evt);
            }
        });

        jButtonClose.setText("Beenden");
        jButtonClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeViewer(evt);
            }
        });

        javax.swing.GroupLayout jPanelBottomGLayout = new javax.swing.GroupLayout(jPanelBottomG);
        jPanelBottomG.setLayout(jPanelBottomGLayout);
        jPanelBottomGLayout.setHorizontalGroup(
            jPanelBottomGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomGLayout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(jButtonConfig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );

        jPanelBottomGLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonClose, jButtonConfig, jButtonNewView});

        jPanelBottomGLayout.setVerticalGroup(
            jPanelBottomGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBottomGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfig)
                    .addComponent(jButtonNewView)
                    .addComponent(jButtonClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMainG.add(jPanelBottomG, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelMainG, java.awt.BorderLayout.CENTER);

        jMenuFile.setText("Datei");

        jMenuItemNewView.setText("Neuer View");
        jMenuItemNewView.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemNewViewActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemNewView);

        jMenuItemConfig.setText("Konfiguration");
        jMenuItemConfig.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemConfigActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemConfig);

        jMenuItemClose.setText("Beenden");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeViewer(evt);
            }
        });
        jMenuFile.add(jMenuItemClose);

        jMenuBar.add(jMenuFile);

        jMenuHelp.setText("Hilfe");

        jMenuItemHelp.setText("Hilfe");
        jMenuHelp.add(jMenuItemHelp);

        jMenuItemAbout.setText("About");
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTab()
    {
        ViewNameChoice vnc = new ViewNameChoice( (JFrame)this.getParent(), true );
        vnc.setVisible(true);
        
        String name = vnc.getName();
        if( name == null )
            return;
        
        ViewerTab jPanelTab = new ViewerTab();
        javax.swing.JPanel jPanelMain = new javax.swing.JPanel();
        javax.swing.JPanel jPanelTop = new javax.swing.JPanel();
        javax.swing.JPanel jPanelBottom = new javax.swing.JPanel();
       
        jPanelTab.setLayout(new java.awt.BorderLayout());
        jPanelTop.setPreferredSize(new java.awt.Dimension(429, 40));
        
        final javax.swing.JTextField filterText = new javax.swing.JTextField();
        javax.swing.JLabel filterLabel = new javax.swing.JLabel();
        javax.swing.JButton jButtonRefresh = new javax.swing.JButton();
        javax.swing.JButton jButtonCloseTab = new javax.swing.JButton();
        javax.swing.JButton jButtonDeleteAll = new javax.swing.JButton();
        javax.swing.JButton jButtonColumnChoice = new javax.swing.JButton();
        
        filterText.setText("");

        filterLabel.setText("Filter");
        filterLabel.setAlignmentX(0.5F);

        jButtonRefresh.setText("Anwenden");
        jButtonRefresh.setMaximumSize(new java.awt.Dimension(100, 20));
        jButtonRefresh.setMinimumSize(new java.awt.Dimension(100, 20));
        jButtonRefresh.setPreferredSize(new java.awt.Dimension(100, 20));
        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(filterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filterText, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRefresh))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterLabel)
                    .addComponent(filterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRefresh))
                .addContainerGap())
        );
        
        
        // Bottom panel
        
        jPanelBottom.setPreferredSize(new java.awt.Dimension(533, 40));
        
        jButtonColumnChoice.setText("Spaltenauswahl");
        jButtonColumnChoice.setToolTipText("");
        jButtonColumnChoice.setActionCommand("");
        jButtonColumnChoice.setMaximumSize(new java.awt.Dimension(110, 23));
        jButtonColumnChoice.setMinimumSize(new java.awt.Dimension(110, 23));
        jButtonColumnChoice.setPreferredSize(new java.awt.Dimension(110, 23));
        jButtonColumnChoice.addActionListener(new java.awt.event.ActionListener()
        {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                openColumnChoiceConfig(evt);
            }
        });

        jButtonCloseTab.setText("Schließen");
        jButtonCloseTab.setToolTipText("");
        jButtonCloseTab.setMaximumSize(new java.awt.Dimension(110, 23));
        jButtonCloseTab.setMinimumSize(new java.awt.Dimension(110, 23));
        jButtonCloseTab.setPreferredSize(new java.awt.Dimension(110, 23));
       
        jButtonDeleteAll.setText("Alle löschen");
        jButtonDeleteAll.setToolTipText("");
        jButtonDeleteAll.setMaximumSize(new java.awt.Dimension(110, 23));
        jButtonDeleteAll.setMinimumSize(new java.awt.Dimension(110, 23));
        jButtonDeleteAll.setPreferredSize(new java.awt.Dimension(110, 23));
       
        
        javax.swing.GroupLayout jPanelBottomLayout = new javax.swing.GroupLayout(jPanelBottom);
        jPanelBottom.setLayout(jPanelBottomLayout);
        jPanelBottomLayout.setHorizontalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBottomLayout.createSequentialGroup()
                .addGap(0, 233, Short.MAX_VALUE)
                .addComponent(jButtonColumnChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCloseTab, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
 
        jPanelBottomLayout.setVerticalGroup(
            jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonColumnChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCloseTab, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
 
        jPanelTab.add(jPanelBottom, java.awt.BorderLayout.SOUTH);
       

        filterText.getAccessibleContext().setAccessibleName("");

        jPanelTab.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanelTab.add(jPanelTop, java.awt.BorderLayout.NORTH);

        jPanelMain.setPreferredSize(new java.awt.Dimension(533, 250));
        jPanelMain.setLayout(new java.awt.BorderLayout());

        javax.swing.JTable jTable = new javax.swing.JTable();
        jTable.setAutoCreateRowSorter(true);
        
        ViewerTableModel model = new ViewerTableModel();
        final Controller controller = new Controller( model );
        jTable.setModel(model);
        model.init( jTable.getColumnModel() );
        
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener()
        {
            @Override 
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                String filter = filterText.getText();
                
                try
                {
                    controller.updateFilter( filter );
                }
                catch( ViewerException ex )
                {
                    JOptionPane.showMessageDialog( null, ex.toString() );                
                }
            }
        });
        
        CellRenderer cr = new CellRenderer( model );
        jTable.setDefaultRenderer( Object.class, cr );
        
        javax.swing.JScrollPane jScrollPane = new javax.swing.JScrollPane();
        jScrollPane.setViewportView(jTable);
        jPanelMain.add(jScrollPane, java.awt.BorderLayout.CENTER);

        jPanelTab.add(jPanelMain, java.awt.BorderLayout.CENTER);

        jTabbedPaneViews.addTab( name , jPanelTab);
        jTabbedPaneViews.setSelectedIndex( jTabbedPaneViews.getTabCount() - 1 );
    }
    
    
    private void newTab(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTab
        // TODO add your handling code here:
        addTab();
    }//GEN-LAST:event_newTab

    private void closeViewer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeViewer
        // TODO add your handling code here:
        int yesNo = JOptionPane.showConfirmDialog (null, "VInfoViewer wird beendet.","VinfoViewer",JOptionPane.OK_CANCEL_OPTION);
        if( yesNo == JOptionPane.OK_OPTION )
        {
            Util.exit(-1);
        }
    }//GEN-LAST:event_closeViewer

    private void openConfigDlg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openConfigDlg
        // TODO add your handling code here:
        ConfigDialog cd = new ConfigDialog(new javax.swing.JFrame(), true);
        cd.setLocationRelativeTo(null);
        cd.setVisible(true);        
    }//GEN-LAST:event_openConfigDlg

    private void openColumnChoiceConfig(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openColumnChoiceConfig
    {//GEN-HEADEREND:event_openColumnChoiceConfig
        // TODO add your handling code here:
        ColumnChoice cc = new ColumnChoice(new javax.swing.JFrame(), true);
        cc.setLocationRelativeTo(null);
        cc.setVisible(true);        
    }//GEN-LAST:event_openColumnChoiceConfig

    private void jMenuItemNewViewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemNewViewActionPerformed
    {//GEN-HEADEREND:event_jMenuItemNewViewActionPerformed
        newTab(evt);
    }//GEN-LAST:event_jMenuItemNewViewActionPerformed

    private void jMenuItemConfigActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemConfigActionPerformed
    {//GEN-HEADEREND:event_jMenuItemConfigActionPerformed
        openConfigDlg( evt );
    }//GEN-LAST:event_jMenuItemConfigActionPerformed

    private void initSystem()
    {
        Util.init();
        system.init();
        jPanelTabT.setVisible( false );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VInfoViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VInfoViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VInfoViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VInfoViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VInfoViewer dialog = new VInfoViewer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        java.lang.System.exit(0);
                    }
                });
                
                dialog.initSystem();
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCloseTabT;
    private javax.swing.JButton jButtonColumnChoiceT;
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonDeleteAllT;
    private javax.swing.JButton jButtonNewView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemConfig;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemNewView;
    private javax.swing.JPanel jPanelBottomG;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelMainG;
    private javax.swing.JPanel jPanelTabBottomT;
    private javax.swing.JPanel jPanelTabT;
    private javax.swing.JPanel jPanelTabTableT;
    private javax.swing.JPanel jPanelTabTopT;
    private javax.swing.JScrollPane jScrollPaneT;
    private javax.swing.JTabbedPane jTabbedPaneViews;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
